### ISSUE TITLE
Should ignore remote dependencies

### ISSUE THREAD

**Issue by matthewmueller** [dominicbarnes/rework-custom-import#2]
Currently breaks with something like:

```css
@import url('https://fonts.googleapis.com/css?family=Assistant');

html {
  margin: 10px;
}
```
